services:
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
          target: /app
        - action: rebuild
          path: ./frontend/package-lock.json
          target: /app
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: rebuild
          path: ./frontend
          target: /static
