version: "3.9"
services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "8080:80"
    volumes:
      - ../frontend/build:/usr/share/caddy
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "8081:3000"
  #   environment:
  #     - NODE_ENV=production
